"""add_major_junction

Revision ID: 3768f0350384
Revises: 84aa889c1e05
Create Date: 2026-10-06 13:35:13.192450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3768f0350384'
down_revision: Union[str, Sequence[str], None] = '84aa889c1e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('majors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('major_courses',
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.PrimaryKeyConstraint('major_id', 'course_id')
    )
    op.drop_column('courses', 'major')
    op.add_column('students', sa.Column('major_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'majors', ['major_id'], ['id'])
    op.drop_column('students', 'major')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('major', sa.VARCHAR(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'major_id')
    op.add_column('courses', sa.Column('major', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('major_courses')
    op.drop_table('majors')
    # ### end Alembic commands ###
