"""add_major_to_student_and_course

Revision ID: 84aa889c1e05
Revises: d39ab51ea44c
Create Date: 2026-10-06 13:32:02.719790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84aa889c1e05'
down_revision: Union[str, Sequence[str], None] = 'd39ab51ea44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('major', sa.String(), nullable=True))
    op.add_column('students', sa.Column('major', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'major')
    op.drop_column('courses', 'major')
    # ### end Alembic commands ###
