"""Add course info fields

Revision ID: d0e163ce1935
Revises: 001
Create Date: 2026-10-05 19:25:41.211464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e163ce1935'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_classes', sa.Column('room', sa.String(), nullable=True))
    op.add_column('course_classes', sa.Column('lecturer', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('name', sa.String(), server_default='Unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'name')
    op.drop_column('course_classes', 'lecturer')
    op.drop_column('course_classes', 'room')
    # ### end Alembic commands ###
