"""Add RegistrationSession fields and AuditLog

Revision ID: d39ab51ea44c
Revises: d0e163ce1935
Create Date: 2026-10-05 19:48:04.693403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39ab51ea44c'
down_revision: Union[str, Sequence[str], None] = 'd0e163ce1935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_class_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_class_id'], ['course_classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('registration_sessions', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('registration_sessions', sa.Column('is_cancelled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration_sessions', 'is_cancelled')
    op.drop_column('registration_sessions', 'end_time')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
